<header id="header" class="header">
    <div class="header-container">
        <div class="features">
            <a href="#" class="logo">
                <figure><img src="../assets/images/logo/logo.svg" alt="Logo" loading="lazy" /></figure>
            </a>
            <a href="#" class="logo logo2">
                <figure><img src="../assets/images/logo/logo-2.svg" alt="Logo" loading="lazy" /></figure>
            </a>
            <?php require_once 'menu.phtml'; ?>
            <div class="login">
                <a href="#" class="enter">Sign In</a>
                <a href="#" class="exit button">Sign Up</a>
            </div>
            <div class="menu-mobile">
                <span class="icon">
                    <i class="fas fa-bars"></i>
                    <i class="fas fa-times"></i>
                </span>
            </div>
        </div>
    </div>
</header>