<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Aqui vem a descrição!">
    <link rel="shortcut icon" href="../assets/images/favicon.svg" type="image/x-icon">

    <!-- Features -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <script type="text/javascript" src="../lib/jquery-3.6.0.min.js"></script>

    <!-- Files CSS -->
    <link rel="stylesheet" href="../assets/css/styles.css" type="text/css" />
    <link rel="stylesheet" href="../assets/css/general.css" type="text/css" />
    <link rel="stylesheet" href="../assets/css/layout/home.css" type="text/css" />

    <!-- Files CSS Mobile -->
    <link rel="stylesheet" href="../assets/css/layout/mobile/home.css" type="text/css" />

    <!-- Files JS -->
    <script type="text/javascript" src="../assets/js/geral.js" async></script>

    <title>Template 02</title>
</head>